### ISSUE TITLE
Vue.js vue-advanced-cropper error

### ISSUE THREAD

**Issue by igogoson** [Norserium/vue-advanced-cropper#34] opened 2020-01-23 19:02 UTC
When I select an image it is continuously cropping the image in a loop until it can't crop anymore. I am getting this error in my logs

app.js:81265 Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.

**Comment by Norserium** [comment] 2020-01-23 21:59
Hello, @igogoson! I suppose, that you use the same variable for `src` prop and for storing the cropper result. You shouldn't do it, because you will get the recursion.

**Comment by TitanFighter** [comment] 2020-01-26 14:29
Just had the same issue.

What I have:
```
// Upload file
<b-form-file
    v-model="avatarFile"
    :state="Boolean(avatarFile)"
    accept="image/jpeg, image/png, image/gif"
/>
```

```
// Convert uploaded file to Base64 and give it to Cropper
const reader = new FileReader()
reader.onload = e => {
    this.imageToCropLinkOrBase64 = e.target.result
}
reader.readAsDataURL(this.avatarFile)
this.$bvModal.show('avatar-cropper-modal')
```

```
// Cropper
<b-modal
    id="avatar-cropper-modal"
    title="Create User"
    @ok="addNewUser"
>
    <cropper
        classname="cropper"
        :src="imageToCropLinkOrBase64"
        :stencil-props="{ aspectRatio: 10/12 }"
        @change="change"
    />
</b-modal>
```

The problem is within Converter code. I upload an 2.5MB image. The image has not uploaded, but modal with cropper already opened (i.e. opened without image). So, I needed to move modal opening inside `reader.onload`, like this:
```
reader.onload = e => {
    this.imageToCropLinkOrBase64 = e.target.result
    this.$bvModal.show('avatar-cropper-modal')
}
```

This fixed the issue.

**Comment by Norserium** [comment] 2020-01-26 19:15
@TitanFighter, are you saying, that you has the following error?

> app.js:81265 Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.

Have you encountered the recursive cropping?

**Comment by TitanFighter** [comment] 2020-01-26 19:52
> are you saying, that you has the following error?
Yes
> Have you encountered the recursive cropping?
No. Maybe because I save cropped image to `this.croppedImage`, not shown above.

**Comment by Norserium** [comment] 2020-01-27 12:53
> No. Maybe because I save cropped image to this.croppedImage, not shown above.

It makes your issue different than issue of @igogoson, and I still should investigate it carefully. I would be grateful for codesandbox that reproduces your problem.

**Comment by igogoson** [comment] 2020-01-27 19:17
My problem comes when I do at @change="onChange". I can not read the canvas and yet I am using the exact code on your documentation. The image crops infinitely and I get the following error [Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'toDataURL' of undefined"

my onChange function  is

onChange({coordinates, canvas}) {
                this.coordinates = coordinates
                // You able to do different manipulations at a canvas
                // but there we just get a cropped image
                this.image = canvas.toDataURL()
            }

and cropper looks like this

 <Cropper
                        classname="upload-example-cropper"
                        :src="image"
                        @change="onChange"
                    />

**Comment by igogoson** [comment] 2020-01-27 20:49
Here is the link to the code. when I add @change method this happens

https://codesandbox.io/embed/vue-advanced-cropper-rotate-bio7o?fontsize=14&hidenavigation=1&theme=dark

**Comment by TitanFighter** [comment] 2020-01-29 11:15
@Norserium this is the [demo](https://codesandbox.io/s/vue-cropper-issue-demo-cy8ky) you requested.

In codesandbox it works. I even tried to upload 10 mb photo + additionally tried to simulate a delay using setTimeout - still works :)

Probably I will be able to play a bit more locally with my project during the upcoming weekend in order to double-check the problem and inform you about the result.

**Comment by Norserium** [comment] 2020-01-29 21:37
@igogoson, there is an error in your codesandbox.

Pay attention, you use the `this.image` as the source image:
```html
<Cropper class="upload-example-cropper" :src="image" @change="onChange"/>
```

But you put the result in the same variable:
```js
onChange({coordinates, canvas}) {
	this.coordinates = coordinates
	// You able to do different manipulations at a canvas
	// but there we just get a cropped image
	this.image = canvas.toDataURL()
},
```

So, it lead to infinite recursion. You update the source image on change, then the cropper gets the updated image and crop it again, and etc.

You shouldn't use the same variable for result image and source. Compare your sandbox with [this sandbox](https://codesandbox.io/s/vue-advanced-cropper-rotate-example-for-github-sni50).

**Comment by Norserium** [comment] 2020-01-29 21:39
@TitanFighter, thank you! If you succeed and catch the reason of this bug, please inform me.

**Comment by TitanFighter** [comment] 2020-02-05 15:40
@Norserium I created a local freshly new project with the code from my linked demo - everything is ok. Probably my current project related issue, so in case if I catch this problem again - I will be back with more details.

**Comment by Norserium** [comment] 2020-02-05 15:42
@TitanFighter, thank you! Keep me informed.

**Comment by Norserium** [comment] 2020-07-11 12:59
@TitanFighter, @igogoson I close this issue, but if you encounter this problem in the future, feel free to write here.

**Closed by Norserium** 2020-07-11 12:59 UTC
