### ISSUE TITLE
Picture zooming doesn't work when using min-height

### ISSUE THREAD

**Issue by sasaorasanin** [Norserium/vue-advanced-cropper#75] opened 2020-09-10 13:55 UTC
`<cropper class="cropper" :src="image" :stencil-props="{ aspectRatio: 1/1 }" stencil-component="circle-stencil" min-height="50%"></cropper>`

When I use min-height, zooming doesn't work :/

**Comment by Norserium** [comment] 2020-09-10 14:41
Hello, @sasaorasanin!

I would be very grateful if any issue was accompanied by a link to codesandbox. I suppose, that the problem is incorrect `min-height` value. You should pass the number to this prop (`0 - 100`), it will be minimum height in the percents of image.

But remember, I plan to change default behavior in `1.0.0` and this prop will accept minimum height in pixels.

**Comment by Norserium** [comment] 2020-10-22 22:44
I close this issue for now. If you still have questions, feel free to ask.

**Closed by Norserium** 2020-10-22 22:44 UTC
