### ISSUE TITLE
Cannot read property 'height' of undefined

### ISSUE THREAD

**Issue by PedroRTomas** [Norserium/vue-advanced-cropper#62] opened 2020-07-09 14:25 UTC
Hello,
I've tried to run the sample available: https://norserium.github.io/vue-advanced-cropper/
But nothing renders on-screen and browser console presents the following errors:
![image](https://user-images.githubusercontent.com/48090914/87051823-fdf50e80-c1f7-11ea-9d94-e1b0121ac7e1.png)
Following the error pointed out it appears to be related with the computed style property.

npm version: 
6.14.5

node version:
v12.18.2

Thanks in advance!

**Comment by Norserium** [comment] 2020-07-10 11:02
Hello, @PedroRTomas! I will investigate this bug on weekends.

**Comment by Norserium** [comment] 2020-07-11 12:57
@PedroRTomas, I've fixed the [example of stencil](https://norserium.github.io/vue-advanced-cropper/introduction/concepts.html#stencil) and added the dynamic component that use one as example below. But I couldn't reproduce exactly your bug. 

Could you share the code?

**Comment by Norserium** [comment] 2020-07-26 13:13
@PedroRTomas, any news?

**Comment by PedroRTomas** [comment] 2020-07-31 13:19
Hi, sorry for the delay
I start thinking that the problem is in the way I'm passing the props to the component, but I'm not totally convinced.
For the example available at the end of the page at https://norserium.github.io/vue-advanced-cropper/ , how would you call it inside of a v-container, for example? And would be mandatory to specify the {height,width, left, top} properties? (The error that I'm getting seems to be related to the fact that I'm not setting stencil-coordinates and when the component tries to read their values ('height' for example, it's trying to read something of 'undefined')

**Comment by Norserium** [comment] 2020-07-31 14:36
@PedroRTomas, could you provide the code details? I still don't get what problem do you encounter. You should set height, width, left and top coordinates of your stencil to correctly place it inside the cropper. How else?

**Comment by PedroRTomas** [comment] 2020-07-31 17:07
> @PedroRTomas, could you provide the code details? I still don't get what problem do you encounter.
Here is a print of the files:
![print_1](https://user-images.githubusercontent.com/48090914/89059012-4a93bb80-d358-11ea-9379-b8b66e3e8623.jpg)
The file on the right is copy-paste of https://norserium.github.io/vue-advanced-cropper/
The problem seems to be that I must be setting wrong the properties of 'StencilCoordinates' within App.vue

**Comment by Norserium** [comment] 2020-07-31 20:02
Why do you use `stencil-example` outside the cropper? It should be [passed to cropper as prop](https://norserium.github.io/vue-advanced-cropper/tutorials/recipes.html).

**Comment by PedroRTomas** [comment] 2020-08-05 11:43
Ok, I've tried doing that and I was able to make cropper example work. However, regarding the stencil example, I still wasn't able to make it functional. Do you provide the full code (HTML and Vue) of an example for that case on your website?

**Comment by Norserium** [comment] 2020-08-09 10:09
There is [the example](https://codesandbox.io/s/vue-avanced-cropper-custom-stencil-8fw9k?file=/src/App.vue).

**Comment by PedroRTomas** [comment] 2020-08-28 10:15
Thanks, I think that now I will be able to use it properly!
Closing, once my original problem is solved.

**Comment by PedroRTomas** [comment] 2020-08-28 12:32
Sorry about this, I thought that I had found the solution, but the truth is that I can't seem to replicate something like this:
![image](https://user-images.githubusercontent.com/48090914/91560717-3086d200-e932-11ea-9a35-4f6893bf00b3.png)

In the example you provided above, the result is still a normal rectangle cropper, despite you pass 'stencil-component' to the Cropper element. 
"
<Cropper
        ref="cropper"
        class="upload-example-cropper"
        :src="image"
        :stencil-component="$options.components.Stencil"
      />
"
My preview:
![image](https://user-images.githubusercontent.com/48090914/91560852-7479d700-e932-11ea-98de-db3fe129e649.png)

More: Placing the code provided in VS Code, and running 'npm run serve' on root project folder the server fails claiming that "Stencil component has been registered, but not used". 
Considering this, could you please edit the example provided?

Thanks a lot!

**Comment by Norserium** [comment] 2020-08-28 14:11
> I thought that I had found the solution, but the truth is that I can't seem to replicate something like this

To replicate something like this, you should customize [the stencil accordingly](https://codesandbox.io/s/vue-avanced-cropper-custom-stencil-2-qogqv).

**Comment by Norserium** [comment] 2020-09-15 08:08
@PedroRTomas, any news?

**Comment by Norserium** [comment] 2020-10-22 22:46
I close this issue for now. If you have questions, feel free to ask.

**Closed by Norserium** 2020-10-22 22:46 UTC
