### ISSUE TITLE
Prop Debounce Should Be Namespaced/Scoped/Renamed

### ISSUE THREAD

**Issue by nickpoulos** [Norserium/vue-advanced-cropper#35] opened 2020-01-29 23:23 UTC
Having a global method/function in our application called debounce is conflicting with the prop `debounce`.  Being that many of the debounce packages provide a function or methods simply named debounce(), maybe the prop could be renamed debounceTime?

Thanks for a great package.

**Comment by Norserium** [comment] 2020-01-30 10:28
Hello, @nickpoulos!

Could you describe how is this prop is conflicting with your global `debounce` function?

**Comment by Norserium** [comment] 2020-02-22 10:36
@nickpoulos, is your issue actual now?

**Comment by Norserium** [comment] 2020-03-24 09:51
@nickpoulos, the described problem looks pretty unfortunate, but I can't reproduce it. Therefore I'm going to close this issue now, but feel free to reopen this issue.

**Closed by Norserium** 2020-03-24 09:51 UTC
