### ISSUE TITLE
Cannot read property 'width' of null

### ISSUE THREAD

**Issue by zaidiqbal** [Norserium/vue-advanced-cropper#73] opened 2020-09-05 13:29 UTC
Getting this error : Uncaught (in promise) TypeError: Cannot read property 'width' of null at VueComponent.resetCoordinates.

I am using cropper inside bootstrap modal, outside bootstrap modal it works fine.

This is how I am using it inside modal:

`<cropper
	class="cropper"
	:src="user.profile_picture"
	:min-height="250"
	:min-width="250"
	:stencil-props="{
		aspectRatio: 1/1,
	}"
	:size-restrictions-algorithm="cropperSizeRestriction">
</cropper>`

May be because modal is initially hidden that is why cropper is unable to find width.

Any solution?

**Comment by Norserium** [comment] 2020-09-06 10:11
Hello, @zaidiqbal! I'm investigating your problem. Codesandbox or source code at least will be helpful.

**Comment by zaidiqbal** [comment] 2020-09-06 10:58
Thanks bro, I am attaching source code file
[MyProfileUpdatePicture.zip](https://github.com/Norserium/vue-advanced-cropper/files/5179512/MyProfileUpdatePicture.zip)

**Comment by Norserium** [comment] 2020-09-06 18:48
@zaidiqbal, could you help to reproduce your bug? Your code fragment is too fragmentary. I've created [the codesandbox example](https://codesandbox.io/s/vue-advanced-cropper-bootstrap-modal-z8y47) that uses bootstrap modal and it works just fine.

**Comment by Norserium** [comment] 2020-09-06 18:55
The working hypothesis: your image is smaller than `250px` width or `250px` height.

**Comment by Norserium** [comment] 2020-09-06 19:00
The working hypothesis: your image width or height is smaller than 250px.

**Comment by Norserium** [comment] 2020-09-06 19:36
Try to update to `0.17.2` version.

**Comment by zaidiqbal** [comment] 2020-09-07 06:22
> The working hypothesis: your image width or height is smaller than 250px.

@Norserium I have tested it on codesandbox, this seems to be the issue. I will further check it on my system

**Comment by Norserium** [comment] 2020-09-07 07:59
@zaidiqbal do the error disappear after update to the newest version?

**Comment by zaidiqbal** [comment] 2020-09-07 08:04
I haven't checked it yet, I installed the library 3-4 days ago so I might be on latest version already.

**Comment by Norserium** [comment] 2020-09-07 08:17
@zaidiqbal I've updated the library yesterday. In the last version I fixed the calculating of width and height in the case, when minimum size greater than maximum. 

The library shouldn't throw the error described above now, but you should check my working hypothesis in any case.

**Comment by zaidiqbal** [comment] 2020-09-07 08:21
Ok thanks, I will give it a try. So in any case image dimensions should be greater than min-width, min-height right? If there comes a smaller image than min-width, min-height then it will again cause this issue?

**Comment by Norserium** [comment] 2020-09-07 08:26
@zaidiqbal if you pass, for example, an image with width lesser than min-width, cropper sets width equal to the image width and blocks resize. It shouldn't produce the error described in this issue anymore.

**Comment by zaidiqbal** [comment] 2020-09-07 08:31
Ok got it, thanks. I will check updated version. Will let you know

**Comment by Norserium** [comment] 2020-09-15 08:07
@zaidiqbal, any news?

**Comment by mathix420** [comment] 2020-09-17 13:41
Hi @Norserium same issue here, 

The issue seams to be caused by `:stencilProps="{aspectRatio: 50/9}"`, if I remove this line everythings is working fine.
The picture I used to get the issue is exactly `2394`w by `3591`h, i haven't try with other portrait mode pics.

```vue
<cropper
    ref="cropper"
    :src="image"
    :sizeRestrictionsAlgorithm="limits"
    :stencilProps="{aspectRatio: 50/9}"
/>
```

```js
limits( props ) {
  const { imageSize } = props
  const bigEnough = imageSize.width >= 1500 && imageSize.height >= 270

  return {
    maxWidth: Infinity,
    maxHeight: Infinity,
    minWidth: bigEnough ? 1500 : 1,
    minHeight: bigEnough ? 270 : 1,
  }
},
```

**Comment by simioluwatomi** [comment] 2020-10-09 15:59
> @zaidiqbal, could you help to reproduce your bug? Your code fragment is too fragmentary. I've created [the codesandbox example](https://codesandbox.io/s/vue-advanced-cropper-bootstrap-modal-z8y47) that uses bootstrap modal and it works just fine.

At first try, this is what happens

![image](https://user-images.githubusercontent.com/22191563/95605353-bed19600-0a50-11eb-9b90-e7b4e610367f.png)

**Comment by isferrei** [comment] 2020-10-20 13:04
Could anyone help to solve this issue? I'm facing same issue even in [https://codesandbox.io/s/vue-advanced-cropper-bootstrap-modal-z8y47] provided by Norserium.

**Comment by isferrei** [comment] 2020-10-20 13:04
@Norserium Could you please try to provide an update fixing this error? It's really hard to work with this tool like that

**Comment by Norserium** [comment] 2020-10-20 15:25
@simioluwatomi this error is fixed in `0.17.3`, but there is another mentioned by our nice guest Isabela.

@isferrei, I'm going to investigate this problem today. Please wait a bit.

**Comment by mathix420** [comment] 2020-10-20 15:43
@Norserium I also got a similar issue with `0.17.3` as mentioned here https://github.com/Norserium/vue-advanced-cropper/issues/73#issuecomment-694243001

**Comment by Norserium** [comment] 2020-10-20 15:47
@mathix420, I've lost your report somehow before, sorry. I'm pretty sure that it's the same issue.

**Comment by Norserium** [comment] 2020-10-20 16:55
@mathix420 try to update to `0.17.4`. I suppose your problem should be solved in this version.

**Comment by mathix420** [comment] 2020-10-21 11:03
@Norserium alright I'm trying that today

**Comment by mathix420** [comment] 2020-10-21 12:25
@Norserium you're right the issue has been fixed by updating to `0.17.4` thanks!

**Comment by Norserium** [comment] 2020-10-25 11:44
@zaidiqbal, @isferrei, @simioluwatomi is this issue still actual (in `0.17.6`)?

**Comment by adenilson-lomybr** [comment] 2020-10-31 01:18
same issue here vue-advanced-cropper@0.17.6

**Comment by Norserium** [comment] 2020-10-31 10:03
@adenilson-lomybr, could you provide codesandbox that illustrates your problem?

**Comment by Norserium** [comment] 2020-11-01 22:18
@adenilson-lomybr try to update to `0.17.7`. I am sure that the reason of the problem is an incorrect combination of size restrictions and cropper height, but the cropper should handle it now.

**Comment by rhysstubbs** [comment] 2020-11-06 17:25
@Norserium 

As @mathix420 said:

> The issue seams to be caused by :stencilProps="{aspectRatio: 50/9}", if I remove this line everythings is working fine

I have just updated to `0.17.7` and I am now seeing this same error. If I remove the stencil prop with ratio then everything looks to be ok.

I am not setting any restrictions, only the stencil ratio, like:

```
<cropper
  ref="cropper16x9"
  class="cropper"
  :stencil-props="{aspectRatio: 16/9}"
  :src="`${selectedPrimaryImage}?v=${nonse}`"
  :key="crop_16x9Image"
  @change="on16x9Change"
/>
```
The full error is:

```
Uncaught (in promise) TypeError: Cannot read property 'width' of null
    at eval (index.es.js?a2c1:1)
    at Array.forEach (<anonymous>)
    at applyTransform (index.es.js?a2c1:1)
    at VueComponent.applyTransform (index.es.js?a2c1:1)
    at VueComponent.resetCoordinates (index.es.js?a2c1:1)
```

**Comment by Norserium** [comment] 2020-11-06 20:44
@rhysstubbs I need more data. Some example (maybe codesandbox) to reproduce this error. I would be very helpful.

**Comment by Norserium** [comment] 2020-11-06 22:16
I've written tests, that I assume cover any possible situations, but `defaultSize` never equals to `null` after refining of size restrictions. Perhaps, size restrictions doesn't recompute in time, but I need to investigate this hypothesis.

**Comment by Norserium** [comment] 2020-11-07 14:19
@rhysstubbs I guess, that cropper is inside the container that has `display: none`. It's the most likely explanation.

**Comment by Norserium** [comment] 2020-11-07 16:36
@rhysstubbs could you update to `0.17.8`? The library processes this situation, but you have to [refresh cropper](https://norserium.github.io/vue-advanced-cropper/guides/advanced-recipes.html#dynamic-cropper-size), when cropper will be displayed.

**Comment by rhysstubbs** [comment] 2020-11-09 08:04
@Norserium 

> @rhysstubbs I guess, that your cropper is inside a container that has `display: none`. It's the most likely explanation.

Correct, it is. I will take a look at updating and implementing the refresh :+1:

**Comment by Norserium** [comment] 2020-11-09 09:26
@rhysstubbs, it's pretty strange that the cropper worked in `16.0.5`. It doesn't produce the error mentioned above, but it doesn't resize cropper on show anyway.

**Comment by rhysstubbs** [comment] 2020-11-09 09:56
@Norserium Hmm, Interesting. I don't have time to do this now but I did very briefly downgrade and immediately saw:

```
TypeError: Cannot read property 'left' of null
  at toLimits(./node_modules/vue-advanced-cropper/dist/index.es.js:1:4359)
  at limitBy(./node_modules/vue-advanced-cropper/dist/index.es.js:1:13874)
  at prepareResult(./node_modules/vue-advanced-cropper/dist/index.es.js:1:61021)
  at o.getResult(./node_modules/vue-advanced-cropper/dist/index.es.js:1:60101)
  at o.getImageCrops(src/mixins/NewsEditorMixin.vue:424:1)
  at o.buildArticleImages(src/mixins/NewsEditorMixin.vue:656:1)
  at o.submit(src/views/news/Create.vue:718:1)
```
You can see as soon as I called `getResult` this was thrown. This may be my implementation and the cropped is hidden and I get the default crop/dimentions from the cropper whether it is/was viisble or not. Not I will take a look into this when I have time :)

**Comment by Norserium** [comment] 2020-11-09 10:25
@rhysstubbs am I right, that this error is in old version? Did you test the last version?

**Comment by mick912** [comment] 2020-11-10 09:23
I also had the same issue. Cropper container was as display: none. instead of display: none I used v-if expression to hide the container. And that approach solved that issue.

**Comment by Norserium** [comment] 2020-11-10 09:26
@mick912 in the latest version it should work even with `display:none`, but you should call [refresh](https://norserium.github.io/vue-advanced-cropper/guides/advanced-recipes.html#dynamic-cropper-size) method when cropper will be displayed.

**Comment by Norserium** [comment] 2020-11-12 13:42
@zaidiqbal, @rhysstubbs, @adenilson-lomybr, @simioluwatomi, @isferrei is this problem still actual (in `0.17.8`)?

**Comment by Norserium** [comment] 2020-11-30 17:45
I assume this issue is solved. Feel free to write if you encounter one in the future.

**Closed by Norserium** 2020-11-30 17:45 UTC

**Comment by qxygene** [comment] 2022-01-14 01:46
1.9.0 same issue !

**Comment by qxygene** [comment] 2022-01-15 00:26
Error in v-on handler: "TypeError: Cannot read properties of null (reading 'width')"

found in

---> <RectangleStencil>
       <TransformableImage>

**Comment by Norserium** [comment] 2022-01-15 09:38
@qxygene, I assume you forgot add something to your message.

**Comment by qxygene** [comment] 2022-01-15 10:31
---> <RectangleStencil>
       <TransformableImage>
         <Anonymous>
           <Cropper>

**Comment by Norserium** [comment] 2022-01-15 11:28
@qxygene I need more details. The source code, for example. The sandbox like [this](https://codesandbox.io/s/vue-avanced-cropper-basic-jfy5w).

**Comment by qxygene** [comment] 2022-01-15 16:13
https://codesandbox.io/s/vue-advanced-cropper-bootstrap-modal-z8y47 

it is same issue, nothing new.

**Comment by Norserium** [comment] 2022-01-15 20:35
@qxygene, are you sure?

I've forked the example above and updated the vue-advanced-cropper to 1.9.0 [here](https://codesandbox.io/s/vue-advanced-cropper-bootstrap-modal-forked-n0lgo).

https://user-images.githubusercontent.com/9862719/149636905-fe9edcd9-d2d5-4310-a3fb-2a853487485c.mp4

Check, that you updated the cropper version.

**Comment by qxygene** [comment] 2022-01-15 21:47
thanks, nut look where the image is. My issue is same, on modal image is not there until you resize browser window. Yo ucan only see a white square and when you click on it you receive error.

**Comment by qxygene** [comment] 2022-01-15 21:50
Full error:

```
Vue warn]: Error in v-on handler: "TypeError: Cannot read properties of null (reading 'width')"

found in

---> <RectangleStencil>
       <TransformableImage>
         <Anonymous>
           <Cropper>
             <VCard>
               <VThemeProvider>
                 <VDialog>
                   <VForm>
                     <Add>
                       <Add> at src/views/Transfer/Add.vue
                         <VMain>
                           <VApp>
                             <App> at src/App.vue
                               <Root>
warn @ vue.runtime.esm.js?2b0e:619
logError @ vue.runtime.esm.js?2b0e:1893
globalHandleError @ vue.runtime.esm.js?2b0e:1888
handleError @ vue.runtime.esm.js?2b0e:1848
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1871
invoker @ vue.runtime.esm.js?2b0e:2188
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1863
Vue.$emit @ vue.runtime.esm.js?2b0e:3903
onResizeEnd @ index.es.js?a2c1:21
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1863
invoker @ vue.runtime.esm.js?2b0e:2188
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1863
Vue.$emit @ vue.runtime.esm.js?2b0e:3903
onEnd @ index.es.js?a2c1:21
drag-end @ index.es.js?a2c1:21
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1863
invoker @ vue.runtime.esm.js?2b0e:2188
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1863
Vue.$emit @ vue.runtime.esm.js?2b0e:3903
onDragEnd @ index.es.js?a2c1:21
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1863
invoker @ vue.runtime.esm.js?2b0e:2188
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1863
Vue.$emit @ vue.runtime.esm.js?2b0e:3903
drag-end @ index.es.js?a2c1:21
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1863
invoker @ vue.runtime.esm.js?2b0e:2188
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1863
Vue.$emit @ vue.runtime.esm.js?2b0e:3903
processEnd @ index.es.js?a2c1:21
onMouseUp @ index.es.js?a2c1:21
vue.runtime.esm.js?2b0e:1897 TypeError: Cannot read properties of null (reading 'width')
    at eval (index.es.js?a2c1:21:1)
    at Array.some (<anonymous>)
    at X (index.es.js?a2c1:21:1)
    at VueComponent.processAutoZoom (index.es.js?a2c1:21:1)
    at VueComponent.runAutoZoom (index.es.js?a2c1:21:1)
    at VueComponent.onResizeEnd (index.es.js?a2c1:21:1)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1863:1)
    at VueComponent.invoker (vue.runtime.esm.js?2b0e:2188:1)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1863:1)
    at VueComponent.Vue.$emit (vue.runtime.esm.js?2b0e:3903:1)
```

**Comment by Norserium** [comment] 2022-01-16 11:23
@qxygene, could you record the video?

I've import the styles and see no problems at all.

https://user-images.githubusercontent.com/9862719/149657846-854fed27-f25e-456a-b3a8-73a7d7cec5a9.mp4

[Sandbox](https://codesandbox.io/s/vue-advanced-cropper-bootstrap-modal-forked-n0lgo?file=/src/App.vue).

**Comment by Norserium** [comment] 2022-01-16 11:28
@qxygene, but I can assume the root of your issue: you should call `refresh` method on modal open.

If the cropper is displayed inside container with `display: none`, it has no height and width. So when the container becomes visible, cropper doesn't know it and still remains without height and width. The calling of [the refresh method](https://norserium.github.io/vue-advanced-cropper/guides/advanced-recipes.html#dynamic-cropper-size) resizes cropper.

**Comment by qxygene** [comment] 2022-01-17 04:59
https://user-images.githubusercontent.com/2819611/149710532-0133c326-1d98-4a4a-b8fd-267cffb1d76b.mp4

**Comment by Norserium** [comment] 2022-01-17 07:10
@qxygene, how is your modal implemented? 

I assume that it doesn't destroy the content (the cropper in this case) on close. The destroying the content on close will solve your problem in two shakes.

Otherwise, try to call `refresh` method on modal open as I wrote above

**Comment by qxygene** [comment] 2022-01-17 13:10
Yes, i dont want it to destroy content, it works bıt when you resize it gives error. Refresh didnt work at all.

**Comment by Norserium** [comment] 2022-01-17 13:11
@qxygene, could you provide the code, where you refresh the cropper?

**Comment by Norserium** [comment] 2022-01-17 23:12
@qxygene, I assume that you refresh the cropper not in the appropriate time. For example, before the modal is actually opened. The part of your source code can give me a clue how to help you.

**Comment by qxygene** [comment] 2022-01-19 01:25
thank you, i will send you email

**Comment by Norserium** [comment] 2022-01-19 10:45
@qxygene, I will wait.
